### ISSUE TITLE
lc show 1 --solution does not work

### ISSUE THREAD

**Issue by yuzhoul1991** [skygragon/leetcode-cli-plugins#11]
Doesn't seem to work after installation for this solution discuss plugin:

 $ lc show 1 --solution                                                           ⬡ 9.4.0
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/home/yuzliu/.nvm/versions/node/v9.4.0/lib/node_modules/leetcode-cli/lib/plugins/solution.discuss.js:54:21)
    at Request.self.callback (/home/yuzliu/.nvm/versions/node/v9.4.0/lib/node_modules/leetcode-cli/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/yuzliu/.nvm/versions/node/v9.4.0/lib/node_modules/leetcode-cli/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/yuzliu/.nvm/versions/node/v9.4.0/lib/node_modules/leetcode-cli/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)

version: 2.5.1
os: Linux redhat

**Comment by yuzhoul1991** [comment]
ok Thanks that works!
