### ISSUE TITLE
Cannot install plugin: Error

### ISSUE THREAD

**Issue by ketankr9** [skygragon/leetcode-cli-plugins#26]
**Error**
```
$$$ leetcode plugin -i cookie.chrome
fs.js:145
    throw err;
    ^

Error: ENOENT: no such file or directory, unlink '/snapshot/leetcode-cli/lib/plugins/cookie.chrome.js'
    at Object.fs.unlinkSync (fs.js:1049:3)
    at Object.file.rm (/snapshot/leetcode-cli/lib/file.js:83:13)
    at WriteStream.<anonymous> (/snapshot/leetcode-cli/lib/plugin.js:170:21)
    at WriteStream.emit (events.js:182:13)
    at fs.close (fs.js:2181:14)
    at zalgoSafe (pkg/prelude/bootstrap.js:256:10)
    at FSReqWrap.oncomplete (fs.js:171:20)
```

**Comment by skygragon** [comment]
@ketankr9 are you using all-in-one binary? then you don't need install plugin since it's all in one now. you should see all plugins via `leetcode ext`

**Comment by ketankr9** [comment]
It's all in one binary, but why is my plugin not active?
```
Active    Name                Version
✘        cookie.chrome      2018.11.18
```
I have configured my extension by: 
```
$$$ leetcode config plugins:cookie.chrome
{
  "profile": "Default"
}

```
Thanks
