### ISSUE TITLE
Login errors out 'Failed to retrieve user favorites: [object Object]'

### ISSUE THREAD

**Issue by Ronll** [skygragon/leetcode-cli-plugins#47]
Getting this when I try to submit:

> [ERROR] session expired, please login again [code=-1]

This when I try to login:

> [DEBUG] running cookie.firefox.login
> [DEBUG] running cookie.firefox.signin
> [DEBUG] try to copy leetcode cookies from firefox ...
> [DEBUG] Successfully copied leetcode cookies!
> [DEBUG] running leetcode.getFavorites
> [DEBUG] http error: 401
> [WARN] Failed to retrieve user favorites: [object Object]
> [DEBUG] running leetcode.getUserInfo
> /home/ron/.nvm/versions/node/v12.18.2/lib/node_modules/leetcode-cli/lib/plugins/leetcode.js:515
>         user.paid = _user.isCurrentUserPremium;
>                           ^
> 
> TypeError: Cannot read property 'isCurrentUserPremium' of null
>     at /home/ron/.nvm/versions/node/v12.18.2/lib/node_modules/leetcode-cli/lib/plugins/leetcode.js:515:27
>     at Request._callback (/home/ron/.nvm/versions/node/v12.18.2/lib/node_modules/leetcode-cli/lib/plugins/leetcode.js:421:12)
>     at Request.self.callback (/home/ron/.nvm/versions/node/v12.18.2/lib/node_modules/leetcode-cli/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:315:20)
>     at Request.<anonymous> (/home/ron/.nvm/versions/node/v12.18.2/lib/node_modules/leetcode-cli/node_modules/request/request.js:1161:10)
>     at Request.emit (events.js:315:20)
>     at IncomingMessage.<anonymous> (/home/ron/.nvm/versions/node/v12.18.2/lib/node_modules/leetcode-cli/node_modules/request/request.js:1083:12)

**Comment by Ronll** [comment]
Issue: new version of ubuntu did not have libsecret-tools

Solution: `sudo apt-get install libsecret-tools`
