### ISSUE TITLE
leetcode.solution - JSON parse error

### ISSUE THREAD

**Issue by jveitchmichaelis** [skygragon/leetcode-cli-plugins#9]
Installed fine, but running the example given:

```bash
$ leetcode show 1 --solution
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/leetcode-cli/lib/plugins/solution.discuss.js:54:21)
    at Request.self.callback (/usr/local/lib/node_modules/leetcode-cli/node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/leetcode-cli/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/leetcode-cli/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
```

[Seems](https://github.com/skygragon/leetcode-cli-plugins/blob/d671ec8bd1f087ef0998c945e04bdce591ce03e6/plugins/solution.discuss.js#L54) like it's an error in parse and it doesn't like the doctype.

**Comment by duyue6002** [comment]
same problem
